version: '3.2'
services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - db-data:/postgres/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
volumes:
  db-data:
